# Generated by Django 4.2.7 on 2023-11-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=200)),
            ],
        ),
    ]
