# Generated by Django 4.2.7 on 2023-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=1234567),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.TextField(default=12345678, max_length=10),
            preserve_default=False,
        ),
    ]
