# Generated by Django 4.2.7 on 2023-11-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_rename_firstname_user_name_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullname',
        ),
    ]
