# Generated by Django 4.2.7 on 2023-11-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_rename_name_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
